services:
  - type: web
    name: callx-server
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
